#version: '3.8'
#
#services:
#  app:
#    image: openjdk:21
#    container_name: tourist-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8085:8085"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tourist?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
#      SPRING_DATASOURCE_USERNAME: root
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#      #SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
#
#    depends_on:
#      - tourist
#    networks:
#      - tourism-network
#
#  tourist:
#    image: mysql:8.0
#    container_name: tourist
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#      MYSQL_DATABASE: tourist
#    ports:
#      - "3306:3306"
#    volumes:
#      - db-data:/var/lib/mysql
#    networks:
#      - tourism-network
#
#networks:
#  tourism-network:
#    driver: bridge
#
#volumes:
#  db-data:
