version: "3.8"

services:
  server:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      - tourist_db
    networks:
      - tourism-network

  tourist_db:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: tourist_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3315:3306"
    volumes:
      - tourist-db:/var/lib/mysql
    networks:
      - tourism-network

networks:
  tourism-network:
    driver: bridge

volumes:
  tourist-db:
